### PR TITLE
fix helm manifest hub tag; fix bad merge

### PR DESCRIPTION
**Pull request by jacob-delgado**
A couple of issues:

Fix bad merge in #507. @howardjohn asked me to use 1.4 sanitization methods.

This PR reverts my PR and uses the code from 1.4 with changes made to manifests/

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]
LGTM if the tests pass. Thanks!

**Comment by jacob-delgado** [comment]
Fixes https://github.com/istio/istio/issues/26920

**Review by howardjohn — APPROVED** [review]

**Pull request merged**
