### PR TITLE
Build 1.5.0 beta.3

### PR DESCRIPTION
**Pull request by dgn**
Should stay on hold until #144 is merged

### CODE REVIEW

**Comment by jwendell** [comment]
Please also hold on until https://github.com/istio/istio/pull/21309 is merged as well.

**Comment by dgn** [comment]
Should also wait on istio/istio#21313

**Comment by ericvn** [comment]
I noted that the base image `istio/base:1.5-dev.1` is several months old and has a fair number of vulnerabilities (34). It might be good to try and get a newer build done and into the beta-3 if possible.

**Comment by dgn** [comment]
> I noted that the base image `istio/base:1.5-dev.1` is several months old and has a fair number of vulnerabilities (34). It might be good to try and get a newer build done and into the beta-3 if possible.

Thank you @ericvn, @fpesce told me that @howardjohn is already on it.

**Comment by ericvn** [comment]
I had Slacked @howardjohn as well since I know he builds and pushes new images for the 1.4.x releases.

**Pull request merged**
