### PR TITLE
Mirroring images to gcr

### PR DESCRIPTION
**Pull request by stewartbutler**
Mirroring docker images to GCR in case the new docker rate limit policies throttle people with large clusters, which could cause an outage if they don't have the images cached locally.

### CODE REVIEW

**Review by howardjohn — APPROVED** [review]

**Comment by howardjohn** [comment]
I think the dryrun test is stale, pointing to envoy-wasm when it should be envoy now

**Comment by stewartbutler** [comment]
@howardjohn Changed the reference from `envoy-wasm` to `envoy`, test is still failing. Looks like it can't find the SHA?

I'm not sure where it is getting the envoy SHA from, so not sure where to start in debugging it.

**Comment by howardjohn** [comment]
Its from `WORKSPACE` in istio/proxy which seems to point to istio/envoy:
```
ENVOY_SHA = "4760a0f90c8fcfa319d699adec21e177cfcb48e2"

ENVOY_SHA256 = "4829a219b4a4bd96dc9f231aec463e34563cea9d942f6eb591cdfe0120d72f12"

ENVOY_ORG = "istio"

ENVOY_REPO = "envoy"
```

**Comment by sdake** [comment]
@stewartbutler as a followup PR, can you add the main.go tool to istio/tools/cmd/imagebuild or whatever main.go does? go run is not ideal, although fine for now.

Cheers,
-steve

**Comment by howardjohn** [comment]
can you fix the merge conflict?

**Comment by stewartbutler** [comment]
Waiting for https://github.com/istio/proxy/pull/3070 to merge to rerun tests

**Comment by howardjohn** [comment]
If I understand it right we need istio/istio to update envoy, which is
blocked by a bunch of things

**Comment by fpesce** [comment]
> s

yep it's right, istio still referencing  c22c655c6c748c29d6b1e30c7bdee4337051c678 from proxy

**Comment by ericvn** [comment]
https://github.com/istio/istio/pull/28500

**Comment by stewartbutler** [comment]
@howardjohn I think this can move forward now

**Comment by howardjohn** [comment]
Should we cherrypick just the publish script to 1.8?

**Pull request merged**
